### ISSUE TITLE
line 131, distance() has only one argument.

### ISSUE THREAD

**Issue by petersoapes** [MatthewWolff/ImageAnalysis#1]
![image](https://cloud.githubusercontent.com/assets/8837154/24808960/87f5c594-1b83-11e7-8274-b522b058c269.png)

**Comment by petersoapes** [comment]
error encountered when using test2.tif file.
Error message links to a line within the distance.m file.  Not clear where the source of the error is in imageAnalysis script.
line 131  distance(bw)  --'not enough input arrguments'

see examples for how to work distance
https://www.mathworks.com/help/map/ref/distance.html

**Comment by petersoapes** [comment]
What is the purpose of calling distance here? What's the goal of defining percentOfImg  ?
distance called on bw, (the segmented centromeres),

**Comment by MatthewWolff** [comment]
Distance isn’t a method but is the name of a variable farther down. It wasn’t supposed to be used here, but instead “sum” was. Every call of the "sum" function was changed to the word "distance" because of a dumb mistake of mine… whoops
And while I do like to be as concise as possible (opting not to assign something to a variable if I’m only going to use it once), I felt it was best here to make it very clear what was happening. It can get very disorienting to see very long lines with many calculations, so I pre-defined it here to make the code self-explanatory.

**Comment by MatthewWolff** [comment]
Reverted accidental name changes
